### ISSUE TITLE
Add support for symfony/filesystem v3.2.0

### ISSUE THREAD

**Issue by chriscarpenter12** [GeckoPackages/GeckoSilexConfigService#16]
Can you add support for `symfony/filesystem v3.2.0`?

**Comment by SpacePossum** [comment]
Hi,
Thanks for the suggestion, I'm happy so support more use cases. I'm not sure how you would the `filesystem` being supported. Is it for support for `readlink` ?

**Comment by SpacePossum** [comment]
Closing as there is no response from the author and I don't know what to do here.
