### ISSUE TITLE
Compatibility with last versions of symfony/filesystem

### ISSUE THREAD

**Issue by agilare** [GeckoPackages/GeckoSilexConfigService#23]
Hello, 

Currently, as noted in https://packagist.org/packages/gecko-packages/gecko-silex-config-service last version of GeckoSilexConfigService is dependent on `symfony/filesystem: ~2.8|3.0.*`

Is a newer version of GeckoSilexConfigService planned, compatible with lasts versions of filesystem ?

**Comment by SpacePossum** [comment]
fixed, I'll release a new version in a bit

**Comment by agilare** [comment]
Thank you, the `composer require gecko-packages/gecko-silex-config-service` works now in my app
